import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  languages: Language[];
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive list of 130+ languages
const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', flag: '🇹🇼' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', flag: '🇧🇾' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', flag: '🇲🇰' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', flag: '🇪🇷' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', flag: '🇳🇬' },
  { code: 'ha', name: 'Hausa', nativeName: 'Harshen Hausa', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', flag: '🇿🇦' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '🇵🇭' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇳🇵' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'my', name: 'Myanmar', nativeName: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', flag: '🇰🇭' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ', flag: '🇱🇦' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', flag: '🇲🇳' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', flag: '🇦🇿' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', flag: '🇰🇿' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргыз', flag: '🇰🇬' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek', flag: '🇺🇿' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen', flag: '🇹🇲' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', flag: '🇹🇯' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', flag: '🇲🇹' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', flag: '🇮🇪' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskera', flag: '🏴󠁥󠁳󠁰󠁶󠁿' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🏴󠁥󠁳󠁣󠁴󠁿' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', flag: '🏴󠁥󠁳󠁧󠁡󠁿' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', flag: '🇱🇺' },
  { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch', flag: '🇨🇭' },
  { code: 'fo', name: 'Faroese', nativeName: 'Føroyskt', flag: '🇫🇴' },
  { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut', flag: '🇬🇱' },
  { code: 'se', name: 'Northern Sami', nativeName: 'Davvisámegiella', flag: '🇸🇪' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག', flag: '🏴󠁣󠁮󠁸󠁺󠁿' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', flag: '🇧🇹' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flag: '🇷🇼' },
  { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi', flag: '🇧🇮' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', flag: '🇲🇬' },
  { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa', flag: '🇲🇼' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona', flag: '🇿🇼' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', flag: '🇱🇸' },
  { code: 'tn', name: 'Setswana', nativeName: 'Setswana', flag: '🇧🇼' },
  { code: 've', name: 'Tshivenda', nativeName: 'Tshivenḓa', flag: '🇿🇦' },
  { code: 'ts', name: 'Xitsonga', nativeName: 'Xitsonga', flag: '🇿🇦' },
  { code: 'ss', name: 'Siswati', nativeName: 'SiSwati', flag: '🇸🇿' },
  { code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele', flag: '🇿🇦' },
  { code: 'nso', name: 'Northern Sotho', nativeName: 'Sepedi', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', nativeName: 'Akan', flag: '🇬🇭' },
  { code: 'tw', name: 'Twi', nativeName: 'Twi', flag: '🇬🇭' },
  { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe', flag: '🇬🇭' },
  { code: 'ff', name: 'Fulah', nativeName: 'Fulfulde', flag: '🇸🇳' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wollof', flag: '🇸🇳' },
  { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan', flag: '🇲🇱' },
  { code: 'dyu', name: 'Dyula', nativeName: 'Dyula', flag: '🇨🇮' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', flag: '🇨🇩' },
  { code: 'kg', name: 'Kongo', nativeName: 'Kikongo', flag: '🇨🇩' },
  { code: 'lua', name: 'Luba-Katanga', nativeName: 'Tshiluba', flag: '🇨🇩' },
  { code: 'sg', name: 'Sango', nativeName: 'Sängö', flag: '🇨🇫' },
  { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu', flag: '🇵🇬' },
  { code: 'tpi', name: 'Tok Pisin', nativeName: 'Tok Pisin', flag: '🇵🇬' },
  { code: 'bi', name: 'Bislama', nativeName: 'Bislama', flag: '🇻🇺' },
  { code: 'fj', name: 'Fijian', nativeName: 'Vosa Vakaviti', flag: '🇫🇯' },
  { code: 'mi', name: 'Māori', nativeName: 'Te Reo Māori', flag: '🇳🇿' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa', flag: '🇼🇸' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea Fakatonga', flag: '🇹🇴' },
  { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti', flag: '🇵🇫' },
  { code: 'na', name: 'Nauru', nativeName: 'Ekakairũ Naoero', flag: '🇳🇷' },
  { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ', flag: '🇲🇭' },
  { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru', flag: '🇬🇺' },
  { code: 'pau', name: 'Palauan', nativeName: 'Tekoi ra Belau', flag: '🇵🇼' },
  { code: 'chk', name: 'Chuukese', nativeName: 'Chuukese', flag: '🇫🇲' },
  { code: 'kos', name: 'Kosraean', nativeName: 'Kosrae', flag: '🇫🇲' },
  { code: 'pon', name: 'Pohnpeian', nativeName: 'Pohnpeian', flag: '🇫🇲' },
  { code: 'yap', name: 'Yapese', nativeName: 'Yapese', flag: '🇫🇲' },
  { code: 'gil', name: 'Gilbertese', nativeName: 'Kiribati', flag: '🇰🇮' },
  { code: 'tvl', name: 'Tuvaluan', nativeName: 'Te Ggana Tuuvalu', flag: '🇹🇻' },
  { code: 'niu', name: 'Niuean', nativeName: 'Ko e Vagahau Niuē', flag: '🇳🇺' },
  { code: 'tkl', name: 'Tokelauan', nativeName: 'Gagana Tokelau', flag: '🇹🇰' },
  { code: 'crs', name: 'Seychellois Creole', nativeName: 'Seselwa', flag: '🇸🇨' },
  { code: 'mfe', name: 'Morisyen', nativeName: 'Kreol morisien', flag: '🇲🇺' },
  { code: 'gcf', name: 'Guadeloupean Creole', nativeName: 'Kréyòl gwadloupéyen', flag: '🇬🇵' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', flag: '🇭🇹' },
  { code: 'pap', name: 'Papiamento', nativeName: 'Papiamentu', flag: '🇦🇼' },
  { code: 'srn', name: 'Sranan Tongo', nativeName: 'Sranan Tongo', flag: '🇸🇷' },
];

// Translation keys for common UI elements
const TRANSLATIONS: Record<string, any> = {
  en: {
    'settings': 'Settings',
    'language': 'Language',
    'search_languages': 'Search languages...',
    'select_language': 'Select Language',
    'save': 'Save',
    'cancel': 'Cancel',
    'dashboard': 'Dashboard',
    'assets': 'Assets',
    'trade': 'Trade',
    'markets': 'Markets',
    'earn': 'Earn',
    'profile': 'Profile',
    'balance': 'Balance',
    'portfolio': 'Portfolio',
    'notifications': 'Notifications',
    'security': 'Security',
    'help': 'Help',
    'logout': 'Logout',
    'welcome': 'Welcome',
    'total_balance': 'Total Balance',
    'buy': 'Buy',
    'sell': 'Sell',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'currency': 'Currency',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'auto': 'Auto',
    'account_info': 'Account Info',
    'profile_picture': 'Profile Picture',
    'nickname': 'Nickname',
    'uid': 'UID',
    'identity_verification': 'Identity Verification',
    'currency_display': 'Currency Display',
    'color_theme': 'Color Theme',
    'screen_lock': 'Screen Lock',
    'fingerprint_login': 'Fingerprint Login',
    'face_id_login': 'Face ID Login',
    'login_notifications': 'Login Notifications',
    'trading_alerts': 'Trading Alerts',
    'price_alerts': 'Price Alerts',
    'news_alerts': 'News Alerts',
    'system_notifications': 'System Notifications',
    'invite_friends': 'Invite Friends',
    'support': 'Support',
    'about': 'About',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'version': 'Version',
    'home': 'Home',
    'convert': 'Convert',
    'my_assets': 'My Assets',
    'total_value': 'Total Value',
    'available_balance': 'Available Balance',
    'frozen_balance': 'Frozen Balance',
    'profit_loss': 'Profit & Loss',
    'today': 'Today',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'all_time': 'All Time',
    'price': 'Price',
    'change': 'Change',
    'volume': 'Volume',
    'market_cap': 'Market Cap',
    'high': 'High',
    'low': 'Low',
    'open': 'Open',
    'close': 'Close',
    'loading': 'Loading...',
    'error': 'Error',
    'try_again': 'Try Again',
    'no_data': 'No Data Available',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'recent': 'Recent',
    'favorites': 'Favorites',
    'watchlist': 'Watchlist',
    'top_gainers': 'Top Gainers',
    'top_losers': 'Top Losers',
    'trending': 'Trending',
    'new_listings': 'New Listings',
    'charts': 'Charts',
    'alerts': 'Alerts',
    'tools': 'Tools',
    'perp': 'Perp',
    'no_active_alerts': 'No active alerts',
    'create_alert': 'Create Alert',
    'trading_tools': 'Trading Tools',
    'order_book': 'Order Book',
    'view_market_depth': 'View market depth',
    'recent_trades': 'Recent Trades',
    'latest_transactions': 'Latest transactions',
    'calculator': 'Calculator',
    'pnl_calculator': 'P&L calculator',
    'analysis': 'Analysis',
    'technical_analysis': 'Technical analysis',
    'market': 'Market',
    'limit': 'Limit',
    'stop': 'Stop',
    'quantity': 'Quantity',
    'long': 'Long',
    'short': 'Short',
    'cross': 'Cross',
    'isolated': 'Isolated',
    'leverage': 'Leverage',
    'margin': 'Margin',
    'available': 'Available',
    'order_type': 'Order Type',
    'price_label': 'Price',
    'value': 'Value',
    'cost': 'Cost',
    'liq_price': 'Liq. Price',
    'tp_sl': 'TP/SL',
    'post_only': 'Post-Only',
    'reduce_only': 'Reduce-Only',
    'orders': 'Orders',
    'positions': 'Positions',
    'borrowings': 'Borrowings',
    'max_buy': 'Max. Buy',
    'order_value': 'Order Value',
    'gtc': 'GTC',
    'earn_title': 'Earn',
    'view_details': 'View Details',
    'flexible_savings': 'Flexible Savings',
    'start_earning_anytime': 'Start earning anytime',
    'fixed_savings': 'Fixed Savings',
    'higher_returns_locked': 'Higher returns, locked terms',
    'staking': 'Staking',
    'stake_earn_rewards': 'Stake and earn rewards',
    'defi_mining': 'DeFi Mining',
    'liquidity_mining_rewards': 'Liquidity mining rewards',
    'popular_savings': 'Popular Savings',
    'min': 'Min',
    'duration': 'Duration',
    'flexible': 'Flexible',
    'days': 'Days',
    'my_products': 'My Products',
    'view_all': 'View All',
    'no_active_products': 'No active products',
    'start_earning_flexible': 'Start earning with flexible savings',
    'start_earning': 'Start Earning',
    'welcome_bonus': 'Welcome Bonus',
    'get_50_usdt_new': 'Get 50 USDT for new users',
    'staking_challenge': 'Staking Challenge',
    'stake_any_amount_win': 'Stake any amount and win',
    'days_left': 'days left',
    'apy': 'APY',
    'futures_trading': 'Futures Trading',
    'spot_trading': 'Spot Trading',
    'kyc_verification': 'KYC Verification',
    'chatbot': 'Chatbot',
    'news': 'News',
    'notification_settings': 'Notification Settings',
    'currency_selection': 'Currency Selection',
    'network_selection': 'Network Selection',
    'crypto_selection': 'Crypto Selection',
    'address_display': 'Address Display',
    'select_crypto': 'Select Crypto',
    'select_network': 'Select Network',
    'deposit_address': 'Deposit Address',
    'minimum_deposit': 'Minimum Deposit',
    'copy_address': 'Copy Address',
    'save_image': 'Save Image',
    'network_fee': 'Network Fee',
    'estimated_time': 'Estimated Time',
    'referral_program': 'Referral Program',
    'total_earnings': 'Total Earnings',
    'total_referrals': 'Total Referrals',
    'monthly_earnings': 'Monthly Earnings',
    'referral_link': 'Referral Link',
    'share_link': 'Share Link',
    'recent_earnings': 'Recent Earnings',
    'no_notifications': 'No notifications',
    'mark_all_read': 'Mark all as read',
    'system_notification': 'System Notification',
    'latest_events': 'Latest Events',
    'announcement': 'Announcement',
    'rewards': 'Rewards',
    'in_app_messages': 'In-App Messages',
    'trading_view_alerts': 'TradingView Alerts',
    'strategy_signal': 'Strategy Signal',
    'account_changes': 'Account Changes',
    'campaigns': 'Campaigns',
    'market_alerts': 'Market Alerts',
    'new_contract_alerts': 'New Contract Alerts',
    'live_chat': 'Live Chat',
    'language_selection': 'Language Selection',
    'select_chat_language': 'Select chat language',
    'end_chat': 'End Chat',
    'chat_history': 'Chat History',
    'type_message': 'Type your message...',
    'send_message': 'Send Message',
    'verification_status': 'Verification Status',
    'upload_documents': 'Upload Documents',
    'personal_info': 'Personal Information',
    'document_verification': 'Document Verification',
    'facial_recognition': 'Facial Recognition',
    'identity_card': 'Identity Card',
    'passport': 'Passport',
    'drivers_license': 'Driver\'s License',
    'take_photo': 'Take Photo',
    'upload_photo': 'Upload Photo',
    'retake': 'Retake',
    'submit': 'Submit',
    'pending': 'Pending',
    'processing': 'Processing',
    'verified': 'Verified',
    'rejected': 'Rejected',
    'live_news': 'Live News',
    'crypto_news': 'Crypto News',
    'breaking_news': 'Breaking News',
    'market_updates': 'Market Updates',
    'read_more': 'Read More',
    'refresh_news': 'Refresh News',
    'connection_status': 'Connection Status',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'last_updated': 'Last Updated',
    'copied': 'Copied',
    'updateFailed': 'Update Failed',
    'invalidFileType': 'Invalid File Type',
    'fileTooLarge': 'File Too Large',
    'uploadFailed': 'Upload Failed',
    'transfer': 'Transfer',
    'lv1_verified': 'Lv.1 Verified',
    'not_verified': 'Not Verified',
    'notification_center': 'Notification Center',
    'help_contact': 'Help & Contact Support',
    'about_us': 'About Us',
    'main_account': 'Main Account',
    'uid_copied': 'UID copied to clipboard',
    'switch_create_account': 'Switch/Create Account',
    'picture_updated_success': 'Your profile picture has been updated successfully.',
    'picture_update_failed': 'Failed to update profile picture. Please try again.',
    'select_image_file': 'Please select an image file.',
    'select_smaller_image': 'Please select an image smaller than 5MB.',
    'failed_to_read_image': 'Failed to read the image file. Please try again.',
    'profile_updated': 'Profile Updated'
  },
  zh: {
    'settings': '设置',
    'language': '语言',
    'search_languages': '搜索语言...',
    'select_language': '选择语言',
    'save': '保存',
    'cancel': '取消',
    'dashboard': '仪表板',
    'assets': '资产',
    'trade': '交易',
    'markets': '市场',
    'earn': '赚取',
    'profile': '个人资料',
    'balance': '余额',
    'portfolio': '投资组合',
    'notifications': '通知',
    'security': '安全',
    'help': '帮助',
    'logout': '登出',
    'welcome': '欢迎',
    'total_balance': '总余额',
    'buy': '买入',
    'sell': '卖出',
    'deposit': '存款',
    'withdraw': '提款',
    'currency': '货币',
    'theme': '主题',
    'dark_mode': '深色模式',
    'light_mode': '浅色模式',
    'auto': '自动',
    'account_info': '账户信息',
    'profile_picture': '头像',
    'nickname': '昵称',
    'uid': '用户ID',
    'identity_verification': '身份验证',
    'currency_display': '货币显示',
    'color_theme': '颜色主题',
    'screen_lock': '屏幕锁定',
    'fingerprint_login': '指纹登录',
    'face_id_login': '面容ID登录',
    'login_notifications': '登录通知',
    'trading_alerts': '交易提醒',
    'price_alerts': '价格提醒',
    'news_alerts': '新闻提醒',
    'system_notifications': '系统通知',
    'invite_friends': '邀请朋友',
    'support': '支持',
    'about': '关于',
    'privacy_policy': '隐私政策',
    'terms_of_service': '服务条款',
    'version': '版本',
    'home': '首页',
    'convert': '兑换',
    'my_assets': '我的资产',
    'total_value': '总价值',
    'available_balance': '可用余额',
    'frozen_balance': '冻结余额',
    'profit_loss': '盈亏',
    'today': '今天',
    'this_week': '本周',
    'this_month': '本月',
    'all_time': '所有时间',
    'price': '价格',
    'change': '变化',
    'volume': '成交量',
    'market_cap': '市值',
    'high': '最高',
    'low': '最低',
    'open': '开盘',
    'close': '收盘',
    'loading': '加载中...',
    'error': '错误',
    'try_again': '重试',
    'no_data': '无数据',
    'search': '搜索',
    'filter': '筛选',
    'sort': '排序',
    'recent': '最近',
    'favorites': '收藏',
    'watchlist': '关注列表',
    'top_gainers': '涨幅榜',
    'top_losers': '跌幅榜',
    'trending': '热门',
    'new_listings': '新上市',
    'charts': '图表',
    'alerts': '提醒',
    'tools': '工具',
    'perp': '永续',
    'no_active_alerts': '无活跃提醒',
    'create_alert': '创建提醒',
    'trading_tools': '交易工具',
    'order_book': '订单簿',
    'view_market_depth': '查看市场深度',
    'recent_trades': '最近交易',
    'latest_transactions': '最新交易',
    'calculator': '计算器',
    'pnl_calculator': '盈亏计算器',
    'analysis': '分析',
    'technical_analysis': '技术分析',
    'market': '市价',
    'limit': '限价',
    'stop': '止损',
    'quantity': '数量',
    'long': '做多',
    'short': '做空',
    'cross': '全仓',
    'isolated': '逐仓',
    'leverage': '杠杆',
    'margin': '保证金',
    'available': '可用',
    'order_type': '订单类型',
    'price_label': '价格',
    'value': '价值',
    'cost': '成本',
    'liq_price': '强平价格',
    'tp_sl': '止盈止损',
    'post_only': '只做市价',
    'reduce_only': '只减仓',
    'orders': '订单',
    'positions': '持仓',
    'borrowings': '借贷',
    'max_buy': '最大买入',
    'order_value': '订单价值',
    'gtc': '取消前有效',
    'earn_title': '理财',
    'view_details': '查看详情',
    'flexible_savings': '活期理财',
    'start_earning_anytime': '随时开始赚取',
    'fixed_savings': '定期理财',
    'higher_returns_locked': '更高收益，锁定期限',
    'staking': '质押',
    'stake_earn_rewards': '质押并赚取奖励',
    'defi_mining': 'DeFi 挖矿',
    'liquidity_mining_rewards': '流动性挖矿奖励',
    'popular_savings': '热门理财',
    'min': '最小',
    'duration': '期限',
    'flexible': '活期',
    'days': '天',
    'my_products': '我的产品',
    'view_all': '查看全部',
    'no_active_products': '无活跃产品',
    'start_earning_flexible': '通过活期理财开始赚取',
    'start_earning': '开始赚取',
    'welcome_bonus': '欢迎奖金',
    'get_50_usdt_new': '新用户获得50 USDT',
    'staking_challenge': '质押挑战',
    'stake_any_amount_win': '质押任意金额即可获胜',
    'days_left': '天剩余',
    'apy': '年化收益率',
    'futures_trading': '期货交易',
    'spot_trading': '现货交易',
    'kyc_verification': 'KYC 身份验证',
    'chatbot': '聊天机器人',
    'news': '新闻',
    'notification_settings': '通知设置',
    'currency_selection': '货币选择',
    'network_selection': '网络选择',
    'crypto_selection': '加密货币选择',
    'address_display': '地址显示',
    'select_crypto': '选择加密货币',
    'select_network': '选择网络',
    'deposit_address': '充值地址',
    'minimum_deposit': '最小充值',
    'copy_address': '复制地址',
    'save_image': '保存图片',
    'network_fee': '网络费用',
    'estimated_time': '预计时间',
    'referral_program': '推荐计划',
    'total_earnings': '总收益',
    'total_referrals': '总推荐人数',
    'monthly_earnings': '月收益',
    'referral_link': '推荐链接',
    'share_link': '分享链接',
    'recent_earnings': '最近收益',
    'no_notifications': '无通知',
    'mark_all_read': '全部标为已读',
    'system_notification': '系统通知',
    'latest_events': '最新事件',
    'announcement': '公告',
    'rewards': '奖励',
    'in_app_messages': '应用内消息',
    'trading_view_alerts': 'TradingView 提醒',
    'strategy_signal': '策略信号',
    'account_changes': '账户变更',
    'campaigns': '活动',
    'market_alerts': '市场提醒',
    'new_contract_alerts': '新合约提醒',
    'live_chat': '在线聊天',
    'language_selection': '语言选择',
    'select_chat_language': '选择聊天语言',
    'end_chat': '结束聊天',
    'chat_history': '聊天记录',
    'type_message': '输入您的消息...',
    'send_message': '发送消息',
    'verification_status': '验证状态',
    'upload_documents': '上传文件',
    'personal_info': '个人信息',
    'document_verification': '文件验证',
    'facial_recognition': '面部识别',
    'identity_card': '身份证',
    'passport': '护照',
    'drivers_license': '驾驶证',
    'take_photo': '拍照',
    'upload_photo': '上传照片',
    'retake': '重拍',
    'submit': '提交',
    'pending': '待处理',
    'processing': '处理中',
    'verified': '已验证',
    'rejected': '已拒绝',
    'live_news': '实时新闻',
    'crypto_news': '加密货币新闻',
    'breaking_news': '突发新闻',
    'market_updates': '市场更新',
    'read_more': '阅读更多',
    'refresh_news': '刷新新闻',
    'connection_status': '连接状态',
    'connected': '已连接',
    'disconnected': '已断开',
    'last_updated': '最后更新',
    'copied': '已复制',
    'updateFailed': '更新失败',
    'invalidFileType': '无效文件类型',
    'fileTooLarge': '文件过大',
    'uploadFailed': '上传失败',
    'transfer': '转账',
    'about_us': '关于我们',
    'main_account': '主账户',
    'uid_copied': 'UID已复制到剪贴板',
    'switch_create_account': '切换/创建账户',
    'picture_updated_success': '您的头像已成功更新。',
    'picture_update_failed': '更新头像失败。请重试。',
    'select_image_file': '请选择图片文件。',
    'select_smaller_image': '请选择小于5MB的图片。',
    'failed_to_read_image': '读取图片文件失败。请重试。',
    'profile_updated': '个人资料已更新'
  },
  ja: {
    'settings': '設定',
    'language': '言語',
    'search_languages': '言語を検索...',
    'select_language': '言語を選択',
    'save': '保存',
    'cancel': 'キャンセル',
    'dashboard': 'ダッシュボード',
    'assets': '資産',
    'trade': '取引',
    'markets': 'マーケット',
    'earn': '収益',
    'profile': 'プロフィール',
    'balance': '残高',
    'portfolio': 'ポートフォリオ',
    'notifications': '通知',
    'security': 'セキュリティ',
    'help': 'ヘルプ',
    'logout': 'ログアウト',
    'welcome': 'ようこそ',
    'total_balance': '総残高',
    'buy': '買い',
    'sell': '売り',
    'deposit': '入金',
    'withdraw': '出金',
    'currency': '通貨',
    'theme': 'テーマ',
    'dark_mode': 'ダークモード',
    'light_mode': 'ライトモード',
    'auto': '自動'
  },
  ko: {
    'settings': '설정',
    'language': '언어',
    'search_languages': '언어 검색...',
    'select_language': '언어 선택',
    'save': '저장',
    'cancel': '취소',
    'dashboard': '대시보드',
    'assets': '자산',
    'trade': '거래',
    'markets': '마켓',
    'earn': '수익',
    'profile': '프로필',
    'balance': '잔고',
    'portfolio': '포트폴리오',
    'notifications': '알림',
    'security': '보안',
    'help': '도움말',
    'logout': '로그아웃',
    'welcome': '환영합니다',
    'total_balance': '총 잔고',
    'buy': '매수',
    'sell': '매도',
    'deposit': '입금',
    'withdraw': '출금',
    'currency': '통화',
    'theme': '테마',
    'dark_mode': '다크 모드',
    'light_mode': '라이트 모드',
    'auto': '자동'
  },
  es: {
    'settings': 'Configuración',
    'language': 'Idioma',
    'search_languages': 'Buscar idiomas...',
    'select_language': 'Seleccionar idioma',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'dashboard': 'Panel de control',
    'assets': 'Activos',
    'trade': 'Comercio',
    'markets': 'Mercados',
    'earn': 'Ganar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Cartera',
    'notifications': 'Notificaciones',
    'security': 'Seguridad',
    'help': 'Ayuda',
    'logout': 'Cerrar sesión',
    'welcome': 'Bienvenido',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depósito',
    'withdraw': 'Retirar',
    'currency': 'Moneda',
    'theme': 'Tema',
    'dark_mode': 'Modo oscuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático'
  },
  ja: {
    'settings': '設定',
    'language': '言語',
    'search_languages': '言語を検索...',
    'select_language': '言語を選択',
    'save': '保存',
    'cancel': 'キャンセル',
    'dashboard': 'ダッシュボード',
    'assets': '資産',
    'trade': '取引',
    'markets': '市場',
    'earn': '収益',
    'profile': 'プロフィール',
    'balance': '残高',
    'portfolio': 'ポートフォリオ',
    'notifications': '通知',
    'security': 'セキュリティ',
    'help': 'ヘルプ',
    'logout': 'ログアウト',
    'welcome': 'ようこそ',
    'total_balance': '総残高',
    'buy': '購入',
    'sell': '売却',
    'deposit': '入金',
    'withdraw': '出金',
    'currency': '通貨',
    'theme': 'テーマ',
    'dark_mode': 'ダークモード',
    'light_mode': 'ライトモード',
    'auto': '自動',
    'loading': '読み込み中...',
    'error': 'エラー',
    'try_again': '再試行',
    'no_data': 'データなし',
    'search': '検索',
    'price': '価格',
    'change': '変動',
    'volume': '出来高',
    'high': '高値',
    'low': '安値',
    'copied': 'コピー済み',
    'transfer': '送金',
    'about_us': '私たちについて'
  },
  ko: {
    'settings': '설정',
    'language': '언어',
    'search_languages': '언어 검색...',
    'select_language': '언어 선택',
    'save': '저장',
    'cancel': '취소',
    'dashboard': '대시보드',
    'assets': '자산',
    'trade': '거래',
    'markets': '마켓',
    'earn': '수익',
    'profile': '프로필',
    'balance': '잔액',
    'portfolio': '포트폴리오',
    'notifications': '알림',
    'security': '보안',
    'help': '도움말',
    'logout': '로그아웃',
    'welcome': '환영합니다',
    'total_balance': '총 잔액',
    'buy': '매수',
    'sell': '매도',
    'deposit': '입금',
    'withdraw': '출금',
    'currency': '통화',
    'theme': '테마',
    'dark_mode': '다크 모드',
    'light_mode': '라이트 모드',
    'auto': '자동',
    'loading': '로딩 중...',
    'error': '오류',
    'try_again': '다시 시도',
    'no_data': '데이터 없음',
    'search': '검색',
    'price': '가격',
    'change': '변동',
    'volume': '거래량',
    'high': '고가',
    'low': '저가',
    'copied': '복사됨',
    'transfer': '전송',
    'about_us': '회사 소개'
  },
  ar: {
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'search_languages': 'البحث عن اللغات...',
    'select_language': 'اختر اللغة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'dashboard': 'لوحة القيادة',
    'assets': 'الأصول',
    'trade': 'التداول',
    'markets': 'الأسواق',
    'earn': 'الربح',
    'profile': 'الملف الشخصي',
    'balance': 'الرصيد',
    'portfolio': 'المحفظة',
    'notifications': 'الإشعارات',
    'security': 'الأمان',
    'help': 'المساعدة',
    'logout': 'تسجيل الخروج',
    'welcome': 'أهلاً وسهلاً',
    'total_balance': 'إجمالي الرصيد',
    'buy': 'شراء',
    'sell': 'بيع',
    'deposit': 'إيداع',
    'withdraw': 'سحب',
    'currency': 'العملة',
    'theme': 'المظهر',
    'dark_mode': 'الوضع المظلم',
    'light_mode': 'الوضع الفاتح',
    'auto': 'تلقائي',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'try_again': 'حاول مرة أخرى',
    'no_data': 'لا توجد بيانات',
    'search': 'بحث',
    'price': 'السعر',
    'change': 'التغيير',
    'volume': 'الحجم',
    'high': 'أعلى',
    'low': 'أدنى',
    'copied': 'تم النسخ',
    'transfer': 'تحويل',
    'about_us': 'من نحن'
  },
  ru: {
    'settings': 'Настройки',
    'language': 'Язык',
    'search_languages': 'Поиск языков...',
    'select_language': 'Выберите язык',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'dashboard': 'Панель управления',
    'assets': 'Активы',
    'trade': 'Торговля',
    'markets': 'Рынки',
    'earn': 'Заработок',
    'profile': 'Профиль',
    'balance': 'Баланс',
    'portfolio': 'Портфель',
    'notifications': 'Уведомления',
    'security': 'Безопасность',
    'help': 'Помощь',
    'logout': 'Выйти',
    'welcome': 'Добро пожаловать',
    'total_balance': 'Общий баланс',
    'buy': 'Купить',
    'sell': 'Продать',
    'deposit': 'Пополнить',
    'withdraw': 'Вывести',
    'currency': 'Валюта',
    'theme': 'Тема',
    'dark_mode': 'Темная тема',
    'light_mode': 'Светлая тема',
    'auto': 'Авто',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'try_again': 'Попробовать снова',
    'no_data': 'Нет данных',
    'search': 'Поиск',
    'price': 'Цена',
    'change': 'Изменение',
    'volume': 'Объем',
    'high': 'Максимум',
    'low': 'Минимум',
    'copied': 'Скопировано',
    'transfer': 'Перевод',
    'about_us': 'О нас'
  },
  fr: {
    'settings': 'Paramètres',
    'language': 'Langue',
    'search_languages': 'Rechercher des langues...',
    'select_language': 'Sélectionner la langue',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'dashboard': 'Tableau de bord',
    'assets': 'Actifs',
    'trade': 'Commerce',
    'markets': 'Marchés',
    'earn': 'Gagner',
    'profile': 'Profil',
    'balance': 'Solde',
    'portfolio': 'Portefeuille',
    'notifications': 'Notifications',
    'security': 'Sécurité',
    'help': 'Aide',
    'logout': 'Déconnexion',
    'welcome': 'Bienvenue',
    'total_balance': 'Solde total',
    'buy': 'Acheter',
    'sell': 'Vendre',
    'deposit': 'Dépôt',
    'withdraw': 'Retirer',
    'currency': 'Devise',
    'theme': 'Thème',
    'dark_mode': 'Mode sombre',
    'light_mode': 'Mode clair',
    'auto': 'Automatique'
  },
  de: {
    'settings': 'Einstellungen',
    'language': 'Sprache',
    'search_languages': 'Sprachen suchen...',
    'select_language': 'Sprache auswählen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'dashboard': 'Dashboard',
    'assets': 'Vermögen',
    'trade': 'Handel',
    'markets': 'Märkte',
    'earn': 'Verdienen',
    'profile': 'Profil',
    'balance': 'Guthaben',
    'portfolio': 'Portfolio',
    'notifications': 'Benachrichtigungen',
    'security': 'Sicherheit',
    'help': 'Hilfe',
    'logout': 'Abmelden',
    'welcome': 'Willkommen',
    'total_balance': 'Gesamtguthaben',
    'buy': 'Kaufen',
    'sell': 'Verkaufen',
    'deposit': 'Einzahlen',
    'withdraw': 'Abheben',
    'currency': 'Währung',
    'theme': 'Design',
    'dark_mode': 'Dunkler Modus',
    'light_mode': 'Heller Modus',
    'auto': 'Automatisch'
  },
  pt: {
    'settings': 'Configurações',
    'language': 'Idioma',
    'search_languages': 'Pesquisar idiomas...',
    'select_language': 'Selecionar idioma',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'dashboard': 'Painel',
    'assets': 'Ativos',
    'trade': 'Negociar',
    'markets': 'Mercados',
    'earn': 'Ganhar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Portfólio',
    'notifications': 'Notificações',
    'security': 'Segurança',
    'help': 'Ajuda',
    'logout': 'Sair',
    'welcome': 'Bem-vindo',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depositar',
    'withdraw': 'Sacar',
    'currency': 'Moeda',
    'theme': 'Tema',
    'dark_mode': 'Modo escuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático',
    // Profile translations
    'profile.updated': 'Perfil Atualizado',
    'profile.pictureUpdatedSuccess': 'Sua foto de perfil foi atualizada com sucesso.',
    'profile.pictureUpdateFailed': 'Falha ao atualizar foto de perfil. Tente novamente.',
    'profile.selectImageFile': 'Por favor, selecione um arquivo de imagem.',
    'profile.selectSmallerImage': 'Por favor, selecione uma imagem menor que 5MB.',
    'profile.failedToReadImage': 'Falha ao ler o arquivo de imagem. Tente novamente.',
    'profile.inviteFriends': 'Convidar Amigos',
    'profile.identityVerification': 'Verificação de Identidade',
    'profile.lv1Verified': 'Nível 1 Verificado',
    'profile.processing': 'Processando',
    'profile.notVerified': 'Não Verificado',
    'profile.security': 'Segurança',
    'profile.notificationCenter': 'Central de Notificações',
    'profile.helpContact': 'Ajuda e Suporte',
    'profile.aboutUs': 'Sobre Nós',
    'profile.mainAccount': 'Conta Principal',
    'profile.uidCopied': 'UID copiado para a área de transferência',
    'profile.switchCreateAccount': 'Trocar/Criar Conta',
    // Auth translations
    'auth.logout': 'Sair',
    // Common translations
    'common.copied': 'Copiado',
    'common.updateFailed': 'Falha na Atualização',
    'common.invalidFileType': 'Tipo de Arquivo Inválido',
    'common.fileTooLarge': 'Arquivo Muito Grande',
    'common.uploadFailed': 'Falha no Upload'
  }
};

// Function to detect browser/device language and find the best match
function detectDeviceLanguage(): Language {
  // Get browser language preferences
  const browserLanguages = [
    navigator.language,
    ...(navigator.languages || [])
  ];

  // Try to find exact match first
  for (const browserLang of browserLanguages) {
    const exactMatch = LANGUAGES.find(lang => 
      lang.code.toLowerCase() === browserLang.toLowerCase()
    );
    if (exactMatch) return exactMatch;
  }

  // Try to find language code match (ignore region)
  for (const browserLang of browserLanguages) {
    const langCode = browserLang.split('-')[0].toLowerCase();
    const codeMatch = LANGUAGES.find(lang => 
      lang.code.split('-')[0].toLowerCase() === langCode
    );
    if (codeMatch) return codeMatch;
  }

  // Default to English if no match found
  return LANGUAGES[0];
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch {
        // If parsing fails, detect device language
        return detectDeviceLanguage();
      }
    }
    // First time user - detect their device language automatically
    return detectDeviceLanguage();
  });

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', JSON.stringify(language));
    
    // Force immediate UI update by updating the document language attribute
    document.documentElement.lang = language.code;
    
    // Dispatch a custom event to notify other components of language change
    window.dispatchEvent(new CustomEvent('languageChanged', { 
      detail: { language } 
    }));
  };

  // Set document language on mount and when language changes
  useEffect(() => {
    document.documentElement.lang = currentLanguage.code;
  }, [currentLanguage]);

  const t = (key: string): string => {
    const languageCode = currentLanguage.code.split('-')[0]; // Handle variants like zh-TW
    const translations = TRANSLATIONS[languageCode] || TRANSLATIONS['en'];
    
    // Handle dotted notation keys like 'profile.inviteFriends'
    if (key.includes('.')) {
      const parts = key.split('.');
      let result: any = translations;
      
      for (const part of parts) {
        result = result?.[part];
        if (!result) break;
      }
      
      // If nested lookup fails, try the full key as-is
      return result || translations[key] || key;
    }
    
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        languages: LANGUAGES,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}