import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  languages: Language[];
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive list of 130+ languages
const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', flag: '🇹🇼' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', flag: '🇧🇾' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', flag: '🇲🇰' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', flag: '🇪🇷' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', flag: '🇳🇬' },
  { code: 'ha', name: 'Hausa', nativeName: 'Harshen Hausa', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', flag: '🇿🇦' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '🇵🇭' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇳🇵' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'my', name: 'Myanmar', nativeName: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', flag: '🇰🇭' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ', flag: '🇱🇦' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', flag: '🇲🇳' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', flag: '🇦🇿' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', flag: '🇰🇿' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргыз', flag: '🇰🇬' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek', flag: '🇺🇿' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen', flag: '🇹🇲' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', flag: '🇹🇯' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', flag: '🇲🇹' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', flag: '🇮🇪' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskera', flag: '🏴󠁥󠁳󠁰󠁶󠁿' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🏴󠁥󠁳󠁣󠁴󠁿' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', flag: '🏴󠁥󠁳󠁧󠁡󠁿' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', flag: '🇱🇺' },
  { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch', flag: '🇨🇭' },
  { code: 'fo', name: 'Faroese', nativeName: 'Føroyskt', flag: '🇫🇴' },
  { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut', flag: '🇬🇱' },
  { code: 'se', name: 'Northern Sami', nativeName: 'Davvisámegiella', flag: '🇸🇪' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག', flag: '🏴󠁣󠁮󠁸󠁺󠁿' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', flag: '🇧🇹' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flag: '🇷🇼' },
  { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi', flag: '🇧🇮' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', flag: '🇲🇬' },
  { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa', flag: '🇲🇼' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona', flag: '🇿🇼' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', flag: '🇱🇸' },
  { code: 'tn', name: 'Setswana', nativeName: 'Setswana', flag: '🇧🇼' },
  { code: 've', name: 'Tshivenda', nativeName: 'Tshivenḓa', flag: '🇿🇦' },
  { code: 'ts', name: 'Xitsonga', nativeName: 'Xitsonga', flag: '🇿🇦' },
  { code: 'ss', name: 'Siswati', nativeName: 'SiSwati', flag: '🇸🇿' },
  { code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele', flag: '🇿🇦' },
  { code: 'nso', name: 'Northern Sotho', nativeName: 'Sepedi', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', nativeName: 'Akan', flag: '🇬🇭' },
  { code: 'tw', name: 'Twi', nativeName: 'Twi', flag: '🇬🇭' },
  { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe', flag: '🇬🇭' },
  { code: 'ff', name: 'Fulah', nativeName: 'Fulfulde', flag: '🇸🇳' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wollof', flag: '🇸🇳' },
  { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan', flag: '🇲🇱' },
  { code: 'dyu', name: 'Dyula', nativeName: 'Dyula', flag: '🇨🇮' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', flag: '🇨🇩' },
  { code: 'kg', name: 'Kongo', nativeName: 'Kikongo', flag: '🇨🇩' },
  { code: 'lua', name: 'Luba-Katanga', nativeName: 'Tshiluba', flag: '🇨🇩' },
  { code: 'sg', name: 'Sango', nativeName: 'Sängö', flag: '🇨🇫' },
  { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu', flag: '🇵🇬' },
  { code: 'tpi', name: 'Tok Pisin', nativeName: 'Tok Pisin', flag: '🇵🇬' },
  { code: 'bi', name: 'Bislama', nativeName: 'Bislama', flag: '🇻🇺' },
  { code: 'fj', name: 'Fijian', nativeName: 'Vosa Vakaviti', flag: '🇫🇯' },
  { code: 'mi', name: 'Māori', nativeName: 'Te Reo Māori', flag: '🇳🇿' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa', flag: '🇼🇸' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea Fakatonga', flag: '🇹🇴' },
  { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti', flag: '🇵🇫' },
  { code: 'na', name: 'Nauru', nativeName: 'Ekakairũ Naoero', flag: '🇳🇷' },
  { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ', flag: '🇲🇭' },
  { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru', flag: '🇬🇺' },
  { code: 'pau', name: 'Palauan', nativeName: 'Tekoi ra Belau', flag: '🇵🇼' },
  { code: 'chk', name: 'Chuukese', nativeName: 'Chuukese', flag: '🇫🇲' },
  { code: 'kos', name: 'Kosraean', nativeName: 'Kosrae', flag: '🇫🇲' },
  { code: 'pon', name: 'Pohnpeian', nativeName: 'Pohnpeian', flag: '🇫🇲' },
  { code: 'yap', name: 'Yapese', nativeName: 'Yapese', flag: '🇫🇲' },
  { code: 'gil', name: 'Gilbertese', nativeName: 'Kiribati', flag: '🇰🇮' },
  { code: 'tvl', name: 'Tuvaluan', nativeName: 'Te Ggana Tuuvalu', flag: '🇹🇻' },
  { code: 'niu', name: 'Niuean', nativeName: 'Ko e Vagahau Niuē', flag: '🇳🇺' },
  { code: 'tkl', name: 'Tokelauan', nativeName: 'Gagana Tokelau', flag: '🇹🇰' },
  { code: 'crs', name: 'Seychellois Creole', nativeName: 'Seselwa', flag: '🇸🇨' },
  { code: 'mfe', name: 'Morisyen', nativeName: 'Kreol morisien', flag: '🇲🇺' },
  { code: 'gcf', name: 'Guadeloupean Creole', nativeName: 'Kréyòl gwadloupéyen', flag: '🇬🇵' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', flag: '🇭🇹' },
  { code: 'pap', name: 'Papiamento', nativeName: 'Papiamentu', flag: '🇦🇼' },
  { code: 'srn', name: 'Sranan Tongo', nativeName: 'Sranan Tongo', flag: '🇸🇷' },
];

// Translation keys for common UI elements
const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    'settings': 'Settings',
    'language': 'Language',
    'search_languages': 'Search languages...',
    'select_language': 'Select Language',
    'save': 'Save',
    'cancel': 'Cancel',
    'dashboard': 'Dashboard',
    'assets': 'Assets',
    'trade': 'Trade',
    'markets': 'Markets',
    'earn': 'Earn',
    'profile': 'Profile',
    'balance': 'Balance',
    'portfolio': 'Portfolio',
    'notifications': 'Notifications',
    'security': 'Security',
    'help': 'Help',
    'logout': 'Logout',
    'welcome': 'Welcome',
    'total_balance': 'Total Balance',
    'buy': 'Buy',
    'sell': 'Sell',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'currency': 'Currency',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'auto': 'Auto',
    'account_info': 'Account Info',
    'profile_picture': 'Profile Picture',
    'nickname': 'Nickname',
    'uid': 'UID',
    'identity_verification': 'Identity Verification',
    'currency_display': 'Currency Display',
    'color_theme': 'Color Theme',
    'screen_lock': 'Screen Lock',
    'fingerprint_login': 'Fingerprint Login',
    'face_id_login': 'Face ID Login',
    'login_notifications': 'Login Notifications',
    'trading_alerts': 'Trading Alerts',
    'price_alerts': 'Price Alerts',
    'news_alerts': 'News Alerts',
    'system_notifications': 'System Notifications',
    'invite_friends': 'Invite Friends',
    'support': 'Support',
    'about': 'About',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'version': 'Version',
    'home': 'Home',
    'spot_trading': 'Spot Trading',
    'futures_trading': 'Futures Trading',
    'convert': 'Convert',
    'my_assets': 'My Assets',
    'total_value': 'Total Value',
    'available_balance': 'Available Balance',
    'frozen_balance': 'Frozen Balance',
    'profit_loss': 'Profit & Loss',
    'today': 'Today',
    'yesterday': 'Yesterday',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'all_time': 'All Time',
    'price': 'Price',
    'change': 'Change',
    'volume': 'Volume',
    'market_cap': 'Market Cap',
    'high': 'High',
    'low': 'Low',
    'open': 'Open',
    'close': 'Close',
    'loading': 'Loading...',
    'error': 'Error',
    'try_again': 'Try Again',
    'no_data': 'No Data Available',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'recent': 'Recent',
    'favorites': 'Favorites',
    'watchlist': 'Watchlist',
    'top_gainers': 'Top Gainers',
    'top_losers': 'Top Losers',
    'trending': 'Trending',
    'new_listings': 'New Listings'
  },
  zh: {
    'settings': '设置',
    'language': '语言',
    'search_languages': '搜索语言...',
    'select_language': '选择语言',
    'save': '保存',
    'cancel': '取消',
    'dashboard': '仪表板',
    'assets': '资产',
    'trade': '交易',
    'markets': '市场',
    'earn': '赚取',
    'profile': '个人资料',
    'balance': '余额',
    'portfolio': '投资组合',
    'notifications': '通知',
    'security': '安全',
    'help': '帮助',
    'logout': '登出',
    'welcome': '欢迎',
    'total_balance': '总余额',
    'buy': '买入',
    'sell': '卖出',
    'deposit': '存款',
    'withdraw': '提款',
    'currency': '货币',
    'theme': '主题',
    'dark_mode': '深色模式',
    'light_mode': '浅色模式',
    'auto': '自动',
    'account_info': '账户信息',
    'profile_picture': '头像',
    'nickname': '昵称',
    'uid': '用户ID',
    'identity_verification': '身份验证',
    'currency_display': '货币显示',
    'color_theme': '颜色主题',
    'screen_lock': '屏幕锁定',
    'fingerprint_login': '指纹登录',
    'face_id_login': '面容ID登录',
    'login_notifications': '登录通知',
    'trading_alerts': '交易提醒',
    'price_alerts': '价格提醒',
    'news_alerts': '新闻提醒',
    'system_notifications': '系统通知',
    'invite_friends': '邀请朋友',
    'support': '支持',
    'about': '关于',
    'privacy_policy': '隐私政策',
    'terms_of_service': '服务条款',
    'version': '版本',
    'home': '首页',
    'spot_trading': '现货交易',
    'futures_trading': '期货交易',
    'convert': '兑换',
    'my_assets': '我的资产',
    'total_value': '总价值',
    'available_balance': '可用余额',
    'frozen_balance': '冻结余额',
    'profit_loss': '盈亏',
    'today': '今天',
    'yesterday': '昨天',
    'this_week': '本周',
    'this_month': '本月',
    'all_time': '所有时间',
    'price': '价格',
    'change': '变化',
    'volume': '成交量',
    'market_cap': '市值',
    'high': '最高',
    'low': '最低',
    'open': '开盘',
    'close': '收盘',
    'loading': '加载中...',
    'error': '错误',
    'try_again': '重试',
    'no_data': '无数据',
    'search': '搜索',
    'filter': '筛选',
    'sort': '排序',
    'recent': '最近',
    'favorites': '收藏',
    'watchlist': '关注列表',
    'top_gainers': '涨幅榜',
    'top_losers': '跌幅榜',
    'trending': '热门',
    'new_listings': '新上市'
  },
  ja: {
    'settings': '設定',
    'language': '言語',
    'search_languages': '言語を検索...',
    'select_language': '言語を選択',
    'save': '保存',
    'cancel': 'キャンセル',
    'dashboard': 'ダッシュボード',
    'assets': '資産',
    'trade': '取引',
    'markets': 'マーケット',
    'earn': '収益',
    'profile': 'プロフィール',
    'balance': '残高',
    'portfolio': 'ポートフォリオ',
    'notifications': '通知',
    'security': 'セキュリティ',
    'help': 'ヘルプ',
    'logout': 'ログアウト',
    'welcome': 'ようこそ',
    'total_balance': '総残高',
    'buy': '買い',
    'sell': '売り',
    'deposit': '入金',
    'withdraw': '出金',
    'currency': '通貨',
    'theme': 'テーマ',
    'dark_mode': 'ダークモード',
    'light_mode': 'ライトモード',
    'auto': '自動'
  },
  ko: {
    'settings': '설정',
    'language': '언어',
    'search_languages': '언어 검색...',
    'select_language': '언어 선택',
    'save': '저장',
    'cancel': '취소',
    'dashboard': '대시보드',
    'assets': '자산',
    'trade': '거래',
    'markets': '마켓',
    'earn': '수익',
    'profile': '프로필',
    'balance': '잔고',
    'portfolio': '포트폴리오',
    'notifications': '알림',
    'security': '보안',
    'help': '도움말',
    'logout': '로그아웃',
    'welcome': '환영합니다',
    'total_balance': '총 잔고',
    'buy': '매수',
    'sell': '매도',
    'deposit': '입금',
    'withdraw': '출금',
    'currency': '통화',
    'theme': '테마',
    'dark_mode': '다크 모드',
    'light_mode': '라이트 모드',
    'auto': '자동'
  },
  es: {
    'settings': 'Configuración',
    'language': 'Idioma',
    'search_languages': 'Buscar idiomas...',
    'select_language': 'Seleccionar idioma',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'dashboard': 'Panel de control',
    'assets': 'Activos',
    'trade': 'Comercio',
    'markets': 'Mercados',
    'earn': 'Ganar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Cartera',
    'notifications': 'Notificaciones',
    'security': 'Seguridad',
    'help': 'Ayuda',
    'logout': 'Cerrar sesión',
    'welcome': 'Bienvenido',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depósito',
    'withdraw': 'Retirar',
    'currency': 'Moneda',
    'theme': 'Tema',
    'dark_mode': 'Modo oscuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático'
  },
  fr: {
    'settings': 'Paramètres',
    'language': 'Langue',
    'search_languages': 'Rechercher des langues...',
    'select_language': 'Sélectionner la langue',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'dashboard': 'Tableau de bord',
    'assets': 'Actifs',
    'trade': 'Commerce',
    'markets': 'Marchés',
    'earn': 'Gagner',
    'profile': 'Profil',
    'balance': 'Solde',
    'portfolio': 'Portefeuille',
    'notifications': 'Notifications',
    'security': 'Sécurité',
    'help': 'Aide',
    'logout': 'Déconnexion',
    'welcome': 'Bienvenue',
    'total_balance': 'Solde total',
    'buy': 'Acheter',
    'sell': 'Vendre',
    'deposit': 'Dépôt',
    'withdraw': 'Retirer',
    'currency': 'Devise',
    'theme': 'Thème',
    'dark_mode': 'Mode sombre',
    'light_mode': 'Mode clair',
    'auto': 'Automatique'
  },
  de: {
    'settings': 'Einstellungen',
    'language': 'Sprache',
    'search_languages': 'Sprachen suchen...',
    'select_language': 'Sprache auswählen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'dashboard': 'Dashboard',
    'assets': 'Vermögen',
    'trade': 'Handel',
    'markets': 'Märkte',
    'earn': 'Verdienen',
    'profile': 'Profil',
    'balance': 'Guthaben',
    'portfolio': 'Portfolio',
    'notifications': 'Benachrichtigungen',
    'security': 'Sicherheit',
    'help': 'Hilfe',
    'logout': 'Abmelden',
    'welcome': 'Willkommen',
    'total_balance': 'Gesamtguthaben',
    'buy': 'Kaufen',
    'sell': 'Verkaufen',
    'deposit': 'Einzahlen',
    'withdraw': 'Abheben',
    'currency': 'Währung',
    'theme': 'Design',
    'dark_mode': 'Dunkler Modus',
    'light_mode': 'Heller Modus',
    'auto': 'Automatisch'
  },
  pt: {
    'settings': 'Configurações',
    'language': 'Idioma',
    'search_languages': 'Pesquisar idiomas...',
    'select_language': 'Selecionar idioma',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'dashboard': 'Painel',
    'assets': 'Ativos',
    'trade': 'Negociar',
    'markets': 'Mercados',
    'earn': 'Ganhar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Portfólio',
    'notifications': 'Notificações',
    'security': 'Segurança',
    'help': 'Ajuda',
    'logout': 'Sair',
    'welcome': 'Bem-vindo',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depositar',
    'withdraw': 'Sacar',
    'currency': 'Moeda',
    'theme': 'Tema',
    'dark_mode': 'Modo escuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch {
        return LANGUAGES[0]; // Default to English
      }
    }
    return LANGUAGES[0]; // Default to English
  });

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', JSON.stringify(language));
  };

  const t = (key: string): string => {
    const languageCode = currentLanguage.code.split('-')[0]; // Handle variants like zh-TW
    const translations = TRANSLATIONS[languageCode] || TRANSLATIONS['en'];
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        languages: LANGUAGES,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}