import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

interface LanguageContextType {
  currentLanguage: Language;
  languages: Language[];
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Comprehensive list of 160+ languages
const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', flag: '🇹🇼' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', flag: '🇫🇮' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', flag: '🇧🇾' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', flag: '🇲🇰' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', flag: '🇰🇪' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', flag: '🇪🇷' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá', flag: '🇳🇬' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', flag: '🇳🇬' },
  { code: 'ha', name: 'Hausa', nativeName: 'Harshen Hausa', flag: '🇳🇬' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', flag: '🇿🇦' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', flag: '🇿🇦' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino', flag: '🇵🇭' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', flag: '🇮🇳' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', flag: '🇳🇵' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'my', name: 'Myanmar', nativeName: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', flag: '🇰🇭' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ', flag: '🇱🇦' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', flag: '🇲🇳' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', flag: '🇦🇿' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', flag: '🇰🇿' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргыз', flag: '🇰🇬' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbek', flag: '🇺🇿' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen', flag: '🇹🇲' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', flag: '🇹🇯' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', flag: '🇲🇹' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', flag: '🇮🇪' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskera', flag: '🏴󠁥󠁳󠁰󠁶󠁿' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🏴󠁥󠁳󠁣󠁴󠁿' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', flag: '🏴󠁥󠁳󠁧󠁡󠁿' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', flag: '🇱🇺' },
  { code: 'rm', name: 'Romansh', nativeName: 'Rumantsch', flag: '🇨🇭' },
  { code: 'fo', name: 'Faroese', nativeName: 'Føroyskt', flag: '🇫🇴' },
  { code: 'kl', name: 'Greenlandic', nativeName: 'Kalaallisut', flag: '🇬🇱' },
  { code: 'se', name: 'Northern Sami', nativeName: 'Davvisámegiella', flag: '🇸🇪' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག', flag: '🏴󠁣󠁮󠁸󠁺󠁿' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', flag: '🇧🇹' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaali', flag: '🇸🇴' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', flag: '🇷🇼' },
  { code: 'rn', name: 'Kirundi', nativeName: 'Ikirundi', flag: '🇧🇮' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', flag: '🇲🇬' },
  { code: 'ny', name: 'Chichewa', nativeName: 'Chichewa', flag: '🇲🇼' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona', flag: '🇿🇼' },
  { code: 'st', name: 'Sesotho', nativeName: 'Sesotho', flag: '🇱🇸' },
  { code: 'tn', name: 'Setswana', nativeName: 'Setswana', flag: '🇧🇼' },
  { code: 've', name: 'Tshivenda', nativeName: 'Tshivenḓa', flag: '🇿🇦' },
  { code: 'ts', name: 'Xitsonga', nativeName: 'Xitsonga', flag: '🇿🇦' },
  { code: 'ss', name: 'Siswati', nativeName: 'SiSwati', flag: '🇸🇿' },
  { code: 'nr', name: 'Southern Ndebele', nativeName: 'isiNdebele', flag: '🇿🇦' },
  { code: 'nso', name: 'Northern Sotho', nativeName: 'Sepedi', flag: '🇿🇦' },
  { code: 'ak', name: 'Akan', nativeName: 'Akan', flag: '🇬🇭' },
  { code: 'tw', name: 'Twi', nativeName: 'Twi', flag: '🇬🇭' },
  { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe', flag: '🇬🇭' },
  { code: 'ff', name: 'Fulah', nativeName: 'Fulfulde', flag: '🇸🇳' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wollof', flag: '🇸🇳' },
  { code: 'bm', name: 'Bambara', nativeName: 'Bamanankan', flag: '🇲🇱' },
  { code: 'dyu', name: 'Dyula', nativeName: 'Dyula', flag: '🇨🇮' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála', flag: '🇨🇩' },
  { code: 'kg', name: 'Kongo', nativeName: 'Kikongo', flag: '🇨🇩' },
  { code: 'lua', name: 'Luba-Katanga', nativeName: 'Tshiluba', flag: '🇨🇩' },
  { code: 'sg', name: 'Sango', nativeName: 'Sängö', flag: '🇨🇫' },
  { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu', flag: '🇵🇬' },
  { code: 'tpi', name: 'Tok Pisin', nativeName: 'Tok Pisin', flag: '🇵🇬' },
  { code: 'bi', name: 'Bislama', nativeName: 'Bislama', flag: '🇻🇺' },
  { code: 'fj', name: 'Fijian', nativeName: 'Vosa Vakaviti', flag: '🇫🇯' },
  { code: 'mi', name: 'Māori', nativeName: 'Te Reo Māori', flag: '🇳🇿' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Samoa', flag: '🇼🇸' },
  { code: 'to', name: 'Tongan', nativeName: 'Lea Fakatonga', flag: '🇹🇴' },
  { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti', flag: '🇵🇫' },
  { code: 'na', name: 'Nauru', nativeName: 'Ekakairũ Naoero', flag: '🇳🇷' },
  { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ', flag: '🇲🇭' },
  { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru', flag: '🇬🇺' },
  { code: 'pau', name: 'Palauan', nativeName: 'Tekoi ra Belau', flag: '🇵🇼' },
  { code: 'chk', name: 'Chuukese', nativeName: 'Chuukese', flag: '🇫🇲' },
  { code: 'kos', name: 'Kosraean', nativeName: 'Kosrae', flag: '🇫🇲' },
  { code: 'pon', name: 'Pohnpeian', nativeName: 'Pohnpeian', flag: '🇫🇲' },
  { code: 'yap', name: 'Yapese', nativeName: 'Yapese', flag: '🇫🇲' },
  { code: 'gil', name: 'Gilbertese', nativeName: 'Kiribati', flag: '🇰🇮' },
  { code: 'tvl', name: 'Tuvaluan', nativeName: 'Te Ggana Tuuvalu', flag: '🇹🇻' },
  { code: 'niu', name: 'Niuean', nativeName: 'Ko e Vagahau Niuē', flag: '🇳🇺' },
  { code: 'tkl', name: 'Tokelauan', nativeName: 'Gagana Tokelau', flag: '🇹🇰' },
  { code: 'crs', name: 'Seychellois Creole', nativeName: 'Seselwa', flag: '🇸🇨' },
  { code: 'mfe', name: 'Morisyen', nativeName: 'Kreol morisien', flag: '🇲🇺' },
  { code: 'gcf', name: 'Guadeloupean Creole', nativeName: 'Kréyòl gwadloupéyen', flag: '🇬🇵' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', flag: '🇭🇹' },
  { code: 'pap', name: 'Papiamento', nativeName: 'Papiamentu', flag: '🇦🇼' },
  { code: 'srn', name: 'Sranan Tongo', nativeName: 'Sranan Tongo', flag: '🇸🇷' },
];

// Translation keys for common UI elements
const TRANSLATIONS: Record<string, any> = {
  en: {
    'settings': 'Settings',
    'language': 'Language',
    'search_languages': 'Search languages...',
    'select_language': 'Select Language',
    'save': 'Save',
    'cancel': 'Cancel',
    'dashboard': 'Dashboard',
    'assets': 'Assets',
    'trade': 'Trade',
    'markets': 'Markets',
    'earn': 'Earn',
    'profile': 'Profile',
    'notifications': 'Notifications',
    'balance': 'Balance',
    'portfolio': 'Portfolio',
    'security': 'Security',
    'help': 'Help',
    'welcome': 'Welcome',
    'total_balance': 'Total Balance',
    'buy': 'Buy',
    'sell': 'Sell',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'currency': 'Currency',
    'theme': 'Theme',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'auto': 'Auto',
    'loading': 'Loading...',
    'error': 'Error',
    'try_again': 'Try Again',
    'no_data': 'No Data Available',
    'search': 'Search',
    'price': 'Price',
    'change': 'Change',
    'volume': 'Volume',
    'high': 'High',
    'low': 'Low',
    'copied': 'Copied',
    'transfer': 'Transfer',
    'hot': 'Hot',
    'gainers': 'Gainers',
    'losers': 'Losers',
    'favorites': 'Favorites',
    'new': 'New',
    'turnover': 'Turnover',
    'spot': 'Spot',
    'futures': 'Futures',
    'convert': 'Convert',
    'earn_crypto': 'Earn Crypto',
    'point_camera_qr': 'Point camera at QR code',
    'camera_access_denied': 'Camera access denied or not available',
    'qr_scanner_not_supported': 'QR scanner not supported on this device',
    'welcome_helper': 'Welcome! How can I assist you today?',
    'quick_actions': 'Quick Actions',
    'watchlist': 'Watchlist',
    'top_movers': 'Top Movers',
    'recent_orders': 'Recent Orders',
    'total_holdings': 'Total Holdings',
    'available': 'Available',
    'in_orders': 'In Orders',
    'pnl_today': 'P&L Today',
    'all_balances': 'All Balances',
    'hide_small_balances': 'Hide Small Balances',
    'estimated_value': 'Estimated Value',
    'last_price': 'Last Price',
    'change_24h': '24h Change',
    'bullish': 'Bullish',
    'bearish': 'Bearish',
    'neutral': 'Neutral',
    'trading_pair': 'Trading Pair',
    'order_type': 'Order Type',
    'side': 'Side',
    'amount': 'Amount',
    'filled': 'Filled',
    'status': 'Status',
    'time': 'Time',
    'open': 'Open',
    'filled_order': 'Filled',
    'cancelled': 'Cancelled',
    'partially_filled': 'Partially Filled',
    'apply_now': 'Apply Now!',
    'derivatives': 'Derivatives',
    'no_favorites_selected': 'No favorites selected',
    'loading_market_data': 'Loading market data...',
    'vol': 'Vol',
    'charts': 'Charts',
    'long': 'Long',
    'short': 'Short',
    'market': 'Market',
    'limit': 'Limit',
    'stop': 'Stop',
    'quantity': 'Quantity',
    'leverage': 'Leverage',
    'order_value': 'Order Value',
    'max_buy': 'Max Buy',
    'tp_sl': 'TP/SL',
    'post_only': 'Post Only',
    'price_label': 'Price',
    'my_assets': 'My Assets',
    'total_value': 'Total Value',
    'available_balance': 'Available Balance',
    'frozen_balance': 'Frozen Balance',
    'profit_loss': 'Profit & Loss',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'all_time': 'All Time',
    'market_cap': 'Market Cap',
    'top_gainers': 'Top Gainers',
    'top_losers': 'Top Losers',
    'notification_settings': 'Notification Settings',
    'notificationSettings': 'Notification Settings',
    'currency_selection': 'Currency Selection',
    'currencySelection': 'Currency Selection',
    'network_selection': 'Network Selection',
    'networkSelection': 'Network Selection',
    'crypto_selection': 'Crypto Selection',
    'cryptoSelection': 'Crypto Selection',
    'address_display': 'Address Display',
    'addressDisplay': 'Address Display',
    'select_crypto': 'Select Crypto',
    'selectCrypto': 'Select Crypto',
    'select_network': 'Select Network',
    'selectNetwork': 'Select Network',
    'deposit_address': 'Deposit Address',
    'depositAddress': 'Deposit Address',
    'minimum_deposit': 'Minimum Deposit',
    'minimumDeposit': 'Minimum Deposit',
    'copy_address': 'Copy Address',
    'copyAddress': 'Copy Address',
    'save_image': 'Save Image',
    'saveImage': 'Save Image',
    'network_fee': 'Network Fee',
    'networkFee': 'Network Fee',
    'estimated_time': 'Estimated Time',
    'estimatedTime': 'Estimated Time',
    'referral_program': 'Referral Program',
    'referralProgram': 'Referral Program',
    'total_earnings': 'Total Earnings',
    'totalEarnings': 'Total Earnings',
    'total_referrals': 'Total Referrals',
    'totalReferrals': 'Total Referrals',
    'monthly_earnings': 'Monthly Earnings',
    'monthlyEarnings': 'Monthly Earnings',
    'referral_link': 'Referral Link',
    'referralLink': 'Referral Link',
    'share_link': 'Share Link',
    'shareLink': 'Share Link',
    'recent_earnings': 'Recent Earnings',
    'recentEarnings': 'Recent Earnings',
    'no_notifications': 'No notifications',
    'mark_all_read': 'Mark all as read',
    'system_notification': 'System Notification',
    'latest_events': 'Latest Events',
    'latestEvents': 'Latest Events',
    'invite_friends': 'Invite Friends',
    'identity_verification': 'Identity Verification',
    'notification_center': 'Notification Center',
    'help_contact': 'Help & Contact',
    'about_us': 'About Us',
    'spot_trading': 'Spot Trading',
    'futures_trading': 'Futures Trading',
    'kyc_verification': 'KYC Verification',
    'logout': 'Logout',
    // Profile specific
    'profile_main_account': 'Main Account',
    'profile_switch_create_account': 'Switch/Create Account',
    'profile_uid_copied': 'UID copied to clipboard',
    // Status messages
    'lv1_verified': 'Lv1 Verified',
    'processing': 'Processing',
    'not_verified': 'Not Verified',
    'profile_updated': 'Profile Updated',
    'picture_updated_success': 'Profile picture updated successfully',
    // Notification settings clean names (without underscores)
    'strategySignal': 'Strategy Signal',
    'tradingViewAlerts': 'TradingView Alerts',
    'accountChanges': 'Account Changes',
    'inAppMessages': 'In-App Messages',
    // Profile menu clean names
    'inviteFriends': 'Invite Friends',
    'identityVerification': 'Identity Verification',
    'notificationCenter': 'Notification Center',
    'helpContact': 'Help & Contact',
    'aboutUs': 'About Us',
    // Earn page clean names
    'flexibleSavings': 'Flexible Savings',
    'startEarningAnytime': 'Start earning anytime',
    'fixedSavings': 'Fixed Savings',
    'higherReturnsLocked': 'Higher returns when locked',
    'stakeEarnRewards': 'Stake and earn rewards',
    'defiMining': 'DeFi Mining',
    'liquidityMiningRewards': 'Liquidity mining rewards',
    // More clean names for various features
    'topMovers': 'Top Movers',
    'recentOrders': 'Recent Orders',
    'totalHoldings': 'Total Holdings',
    'inOrders': 'In Orders',
    'pnlToday': 'P&L Today',
    'allBalances': 'All Balances',
    'hideSmallBalances': 'Hide Small Balances',
    'estimatedValue': 'Estimated Value',
    'lastPrice': 'Last Price',
    'change24h': '24h Change',
    'tradingPair': 'Trading Pair',
    'orderType': 'Order Type',
    'filledOrder': 'Filled',
    'partiallyFilled': 'Partially Filled',
    'applyNow': 'Apply Now!',
    'noFavoritesSelected': 'No favorites selected',
    'loadingMarketData': 'Loading market data...',
    'orderValue': 'Order Value',
    'maxBuy': 'Max Buy',
    'postOnly': 'Post Only',
    'priceLabel': 'Price',
    'myAssets': 'My Assets',
    'totalValue': 'Total Value',
    'availableBalance': 'Available Balance',
    'frozenBalance': 'Frozen Balance',
    'profitLoss': 'Profit & Loss',
    'thisWeek': 'This Week',
    'thisMonth': 'This Month',
    'allTime': 'All Time',
    'marketCap': 'Market Cap',
    'topGainers': 'Top Gainers',
    'topLosers': 'Top Losers',
    // More clean names for common UI elements
    'selectLanguage': 'Select Language',
    'totalBalance': 'Total Balance',
    'darkMode': 'Dark Mode',
    'lightMode': 'Light Mode',
    'tryAgain': 'Try Again',
    'noData': 'No Data Available',
    'earnCrypto': 'Earn Crypto',
    'pointCameraQr': 'Point camera at QR code',
    'cameraAccessDenied': 'Camera access denied or not available',
    'qrScannerNotSupported': 'QR scanner not supported on this device',
    'welcomeHelper': 'Welcome! How can I assist you today?',
    'quickActions': 'Quick Actions',
    'updateFailed': 'Update Failed',
    'picture_update_failed': 'Failed to update profile picture',
    'invalidFileType': 'Invalid File Type',
    'select_image_file': 'Please select an image file',
    'fileTooLarge': 'File Too Large',
    'select_smaller_image': 'Please select an image smaller than 5MB',
    'uploadFailed': 'Upload Failed',
    'failed_to_read_image': 'Failed to read image file',
    'common': {
      'copied': 'Copied'
    },
  },
  zh: {
    'settings': '设置',
    'language': '语言',
    'search_languages': '搜索语言...',
    'select_language': '选择语言',
    'save': '保存',
    'cancel': '取消',
    'dashboard': '仪表板',
    'assets': '资产',
    'trade': '交易',
    'markets': '市场',
    'earn': '赚取',
    'profile': '个人资料',
    'notifications': '通知',
    'balance': '余额',
    'portfolio': '投资组合',
    'help': '帮助',
    'welcome': '欢迎',
    'total_balance': '总余额',
    'buy': '买入',
    'sell': '卖出',
    'deposit': '存款',
    'withdraw': '提款',
    'currency': '货币',
    'theme': '主题',
    'dark_mode': '深色模式',
    'light_mode': '浅色模式',
    'auto': '自动',
    'loading': '加载中...',
    'error': '错误',
    'try_again': '重试',
    'no_data': '无数据',
    'search': '搜索',
    'price': '价格',
    'change': '变化',
    'volume': '成交量',
    'high': '最高',
    'low': '最低',
    'copied': '已复制',
    'transfer': '转账',
    'about_us': '关于我们',
    'invite_friends': '邀请朋友',
    'hot': '热门',
    'gainers': '涨幅榜',
    'losers': '跌幅榜',
    'favorites': '收藏',
    'new': '新币',
    'turnover': '成交额',
    'spot': '现货',
    'futures': '期货',
    'convert': '兑换',
    'earn_crypto': '赚币',
    'point_camera_qr': '将相机对准二维码',
    'camera_access_denied': '相机访问被拒绝或不可用',
    'qr_scanner_not_supported': '此设备不支持二维码扫描',
    'welcome_helper': '欢迎！我能为您做什么？',
    'quick_actions': '快捷操作',
    'watchlist': '关注列表',
    'top_movers': '涨跌排行',
    'recent_orders': '最近订单',
    'total_holdings': '总持仓',
    'available': '可用',
    'in_orders': '委托中',
    'pnl_today': '今日盈亏',
    'all_balances': '全部余额',
    'hide_small_balances': '隐藏小额余额',
    'estimated_value': '估值',
    'last_price': '最新价',
    'change_24h': '24h涨跌',
    'bullish': '看涨',
    'bearish': '看跌',
    'neutral': '中性',
    'trading_pair': '交易对',
    'order_type': '订单类型',
    'side': '方向',
    'amount': '数量',
    'filled': '已成交',
    'status': '状态',
    'time': '时间',
    'open': '开放',
    'filled_order': '已成交',
    'cancelled': '已取消',
    'partially_filled': '部分成交',
    'apply_now': '立即申请！',
    'derivatives': '衍生品',
    'no_favorites_selected': '未选择收藏',
    'loading_market_data': '加载市场数据中...',
    'vol': '成交量',
    'charts': '图表',
    'long': '做多',
    'short': '做空',
    'market': '市价',
    'limit': '限价',
    'stop': '止损',
    'quantity': '数量',
    'leverage': '杠杆'
  },
  ja: {
    'settings': '設定',
    'language': '言語',
    'search_languages': '言語を検索...',
    'select_language': '言語を選択',
    'save': '保存',
    'cancel': 'キャンセル',
    'dashboard': 'ダッシュボード',
    'assets': '資産',
    'trade': '取引',
    'markets': '市場',
    'earn': '収益',
    'profile': 'プロフィール',
    'balance': '残高',
    'portfolio': 'ポートフォリオ',
    'notifications': '通知',
    'security': 'セキュリティ',
    'help': 'ヘルプ',
    'logout': 'ログアウト',
    'welcome': 'ようこそ',
    'total_balance': '総残高',
    'buy': '購入',
    'sell': '売却',
    'deposit': '入金',
    'withdraw': '出金',
    'currency': '通貨',
    'theme': 'テーマ',
    'dark_mode': 'ダークモード',
    'light_mode': 'ライトモード',
    'auto': '自動',
    'loading': '読み込み中...',
    'error': 'エラー',
    'try_again': '再試行',
    'no_data': 'データなし',
    'search': '検索',
    'price': '価格',
    'change': '変動',
    'volume': '出来高',
    'high': '高値',
    'low': '安値',
    'copied': 'コピー済み',
    'transfer': '送金',
    'about_us': '私たちについて',
    'invite_friends': '友達を招待',
    'hot': 'ホット',
    'gainers': '上昇',
    'losers': '下落',
    'favorites': 'お気に入り',
    'new': '新規',
    'turnover': '売上高',
    'spot': 'スポット',
    'futures': '先物',
    'convert': '変換',
    'earn_crypto': '暗号通貨を稼ぐ',
    'derivatives': 'デリバティブ',
    'apply_now': '今すぐ申し込み！',
    'no_favorites_selected': 'お気に入りが選択されていません',
    'loading_market_data': '市場データを読み込み中...',
    'vol': '出来高',
    'bullish': '強気',
    'bearish': '弱気',
    'neutral': '中立'
  },
  ko: {
    'settings': '설정',
    'language': '언어',
    'search_languages': '언어 검색...',
    'select_language': '언어 선택',
    'save': '저장',
    'cancel': '취소',
    'dashboard': '대시보드',
    'assets': '자산',
    'trade': '거래',
    'markets': '마켓',
    'earn': '수익',
    'profile': '프로필',
    'balance': '잔액',
    'portfolio': '포트폴리오',
    'notifications': '알림',
    'security': '보안',
    'help': '도움말',
    'logout': '로그아웃',
    'welcome': '환영합니다',
    'total_balance': '총 잔액',
    'buy': '매수',
    'sell': '매도',
    'deposit': '입금',
    'withdraw': '출금',
    'currency': '통화',
    'theme': '테마',
    'dark_mode': '다크 모드',
    'light_mode': '라이트 모드',
    'auto': '자동',
    'loading': '로딩 중...',
    'error': '오류',
    'try_again': '다시 시도',
    'no_data': '데이터 없음',
    'search': '검색',
    'price': '가격',
    'change': '변동',
    'volume': '거래량',
    'high': '고가',
    'low': '저가',
    'copied': '복사됨',
    'transfer': '전송',
    'about_us': '회사 소개'
  },
  ar: {
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'search_languages': 'البحث عن اللغات...',
    'select_language': 'اختر اللغة',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'dashboard': 'لوحة القيادة',
    'assets': 'الأصول',
    'trade': 'التداول',
    'markets': 'الأسواق',
    'earn': 'الربح',
    'profile': 'الملف الشخصي',
    'balance': 'الرصيد',
    'portfolio': 'المحفظة',
    'notifications': 'الإشعارات',
    'security': 'الأمان',
    'help': 'المساعدة',
    'logout': 'تسجيل الخروج',
    'welcome': 'أهلاً وسهلاً',
    'total_balance': 'إجمالي الرصيد',
    'buy': 'شراء',
    'sell': 'بيع',
    'deposit': 'إيداع',
    'withdraw': 'سحب',
    'currency': 'العملة',
    'theme': 'المظهر',
    'dark_mode': 'الوضع المظلم',
    'light_mode': 'الوضع الفاتح',
    'auto': 'تلقائي',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'try_again': 'حاول مرة أخرى',
    'no_data': 'لا توجد بيانات',
    'search': 'بحث',
    'price': 'السعر',
    'change': 'التغيير',
    'volume': 'الحجم',
    'high': 'أعلى',
    'low': 'أدنى',
    'copied': 'تم النسخ',
    'transfer': 'تحويل',
    'about_us': 'من نحن'
  },
  ru: {
    'settings': 'Настройки',
    'language': 'Язык',
    'search_languages': 'Поиск языков...',
    'select_language': 'Выберите язык',
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'dashboard': 'Панель управления',
    'assets': 'Активы',
    'trade': 'Торговля',
    'markets': 'Рынки',
    'earn': 'Заработок',
    'profile': 'Профиль',
    'balance': 'Баланс',
    'portfolio': 'Портфель',
    'notifications': 'Уведомления',
    'security': 'Безопасность',
    'help': 'Помощь',
    'logout': 'Выйти',
    'welcome': 'Добро пожаловать',
    'total_balance': 'Общий баланс',
    'buy': 'Купить',
    'sell': 'Продать',
    'deposit': 'Пополнить',
    'withdraw': 'Вывести',
    'currency': 'Валюта',
    'theme': 'Тема',
    'dark_mode': 'Темная тема',
    'light_mode': 'Светлая тема',
    'auto': 'Авто',
    'loading': 'Загрузка...',
    'error': 'Ошибка',
    'try_again': 'Попробовать снова',
    'no_data': 'Нет данных',
    'search': 'Поиск',
    'price': 'Цена',
    'change': 'Изменение',
    'volume': 'Объем',
    'high': 'Максимум',
    'low': 'Минимум',
    'copied': 'Скопировано',
    'transfer': 'Перевод',
    'about_us': 'О нас'
  },
  fr: {
    'settings': 'Paramètres',
    'language': 'Langue',
    'search_languages': 'Rechercher des langues...',
    'select_language': 'Sélectionner la langue',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'dashboard': 'Tableau de bord',
    'assets': 'Actifs',
    'trade': 'Commerce',
    'markets': 'Marchés',
    'earn': 'Gagner',
    'profile': 'Profil',
    'balance': 'Solde',
    'portfolio': 'Portefeuille',
    'notifications': 'Notifications',
    'security': 'Sécurité',
    'help': 'Aide',
    'logout': 'Déconnexion',
    'welcome': 'Bienvenue',
    'total_balance': 'Solde total',
    'buy': 'Acheter',
    'sell': 'Vendre',
    'deposit': 'Dépôt',
    'withdraw': 'Retirer',
    'currency': 'Devise',
    'theme': 'Thème',
    'dark_mode': 'Mode sombre',
    'light_mode': 'Mode clair',
    'auto': 'Automatique',
    'loading': 'Chargement...',
    'error': 'Erreur',
    'try_again': 'Essayer encore',
    'no_data': 'Aucune donnée',
    'search': 'Rechercher',
    'price': 'Prix',
    'change': 'Changement',
    'volume': 'Volume',
    'high': 'Haut',
    'low': 'Bas',
    'copied': 'Copié',
    'transfer': 'Transférer',
    'about_us': 'À propos de nous'
  },
  de: {
    'settings': 'Einstellungen',
    'language': 'Sprache',
    'search_languages': 'Sprachen suchen...',
    'select_language': 'Sprache auswählen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'dashboard': 'Dashboard',
    'assets': 'Vermögen',
    'trade': 'Handel',
    'markets': 'Märkte',
    'earn': 'Verdienen',
    'profile': 'Profil',
    'balance': 'Guthaben',
    'portfolio': 'Portfolio',
    'notifications': 'Benachrichtigungen',
    'security': 'Sicherheit',
    'help': 'Hilfe',
    'logout': 'Abmelden',
    'welcome': 'Willkommen',
    'total_balance': 'Gesamtguthaben',
    'buy': 'Kaufen',
    'sell': 'Verkaufen',
    'deposit': 'Einzahlen',
    'withdraw': 'Abheben',
    'currency': 'Währung',
    'theme': 'Design',
    'dark_mode': 'Dunkler Modus',
    'light_mode': 'Heller Modus',
    'auto': 'Automatisch',
    'loading': 'Laden...',
    'error': 'Fehler',
    'try_again': 'Erneut versuchen',
    'no_data': 'Keine Daten',
    'search': 'Suchen',
    'price': 'Preis',
    'change': 'Änderung',
    'volume': 'Volumen',
    'high': 'Hoch',
    'low': 'Niedrig',
    'copied': 'Kopiert',
    'transfer': 'Übertragen',
    'about_us': 'Über uns'
  },
  es: {
    'settings': 'Configuración',
    'language': 'Idioma',
    'search_languages': 'Buscar idiomas...',
    'select_language': 'Seleccionar idioma',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'dashboard': 'Tablero',
    'assets': 'Activos',
    'trade': 'Comercio',
    'markets': 'Mercados',
    'earn': 'Ganar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Cartera',
    'notifications': 'Notificaciones',
    'security': 'Seguridad',
    'help': 'Ayuda',
    'logout': 'Cerrar sesión',
    'welcome': 'Bienvenido',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depósito',
    'withdraw': 'Retirar',
    'currency': 'Moneda',
    'theme': 'Tema',
    'dark_mode': 'Modo oscuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático',
    'loading': 'Cargando...',
    'error': 'Error',
    'try_again': 'Intentar de nuevo',
    'no_data': 'Sin datos',
    'search': 'Buscar',
    'price': 'Precio',
    'change': 'Cambio',
    'volume': 'Volumen',
    'high': 'Alto',
    'low': 'Bajo',
    'copied': 'Copiado',
    'transfer': 'Transferir',
    'about_us': 'Acerca de nosotros'
  },
  pt: {
    'settings': 'Configurações',
    'language': 'Idioma',
    'search_languages': 'Pesquisar idiomas...',
    'select_language': 'Selecionar idioma',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'dashboard': 'Painel',
    'assets': 'Ativos',
    'trade': 'Negociar',
    'markets': 'Mercados',
    'earn': 'Ganhar',
    'profile': 'Perfil',
    'balance': 'Saldo',
    'portfolio': 'Portfólio',
    'notifications': 'Notificações',
    'security': 'Segurança',
    'help': 'Ajuda',
    'logout': 'Sair',
    'welcome': 'Bem-vindo',
    'total_balance': 'Saldo total',
    'buy': 'Comprar',
    'sell': 'Vender',
    'deposit': 'Depósito',
    'withdraw': 'Retirar',
    'currency': 'Moeda',
    'theme': 'Tema',
    'dark_mode': 'Modo escuro',
    'light_mode': 'Modo claro',
    'auto': 'Automático',
    'loading': 'Carregando...',
    'error': 'Erro',
    'try_again': 'Tentar novamente',
    'no_data': 'Sem dados',
    'search': 'Pesquisar',
    'price': 'Preço',
    'change': 'Mudança',
    'volume': 'Volume',
    'high': 'Alto',
    'low': 'Baixo',
    'copied': 'Copiado',
    'transfer': 'Transferir',
    'about_us': 'Sobre nós'
  }
};

// Function to detect browser/device language and find the best match
function detectDeviceLanguage(): Language {
  // Get browser language preferences
  const browserLanguages = [
    navigator.language,
    ...(navigator.languages || [])
  ];

  // Try to find exact match first
  for (const browserLang of browserLanguages) {
    const exactMatch = LANGUAGES.find(lang => 
      lang.code.toLowerCase() === browserLang.toLowerCase()
    );
    if (exactMatch) return exactMatch;
  }

  // Try to find language code match (ignore region)
  for (const browserLang of browserLanguages) {
    const langCode = browserLang.split('-')[0].toLowerCase();
    const codeMatch = LANGUAGES.find(lang => 
      lang.code.split('-')[0].toLowerCase() === langCode
    );
    if (codeMatch) return codeMatch;
  }

  // Default to English if no match found
  return LANGUAGES[0];
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('selectedLanguage');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch {
        // If parsing fails, detect device language
        return detectDeviceLanguage();
      }
    }
    // First time user - detect their device language automatically
    return detectDeviceLanguage();
  });

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
    localStorage.setItem('selectedLanguage', JSON.stringify(language));

    // Force immediate UI update by updating the document language attribute
    document.documentElement.lang = language.code;

    // Dispatch a custom event to notify other components of language change
    window.dispatchEvent(new CustomEvent('languageChanged', { 
      detail: { language } 
    }));
  };

  // Set document language on mount and when language changes
  useEffect(() => {
    document.documentElement.lang = currentLanguage.code;
  }, [currentLanguage]);

  const t = (key: string): string => {
    const languageCode = currentLanguage.code.split('-')[0]; // Handle variants like zh-TW
    const translations = TRANSLATIONS[languageCode] || TRANSLATIONS['en'];

    // Handle dotted notation keys like 'profile.inviteFriends'
    if (key.includes('.')) {
      const parts = key.split('.');
      let result: any = translations;

      for (const part of parts) {
        result = result?.[part];
        if (!result) break;
      }

      // If nested lookup fails, try the full key as-is
      return result || translations[key] || key;
    }

    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        languages: LANGUAGES,
        setLanguage,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}